version: "3"

services:
  finance-api:
    build:
      context: .
    volumes:
      - ./:/finance
    container_name: finance-graphql
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    expose:
      - "${PORT}"
    networks:
      - finance
  financedb:
    image: postgres:15
    hostname: postgres
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data:z
    container_name: finance-db
    ports:
      - "5432:5432"
    expose:
      - 5432
    networks:
      - finance
networks:
  finance:
    driver: bridge
