version: "3"

services:
  db:
    image: postgres:15
    hostname: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    # volumes:
    #   - ./postgres:/var/lib/postgresql/data:z
    container_name: db
    ports:
      - "5432:5432"
    networks:
      - finance
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: finance-graphql
    env_file:
      - .env
    ports:
      - "${PORT}:${PORT}"
    networks:
      - finance
    depends_on:
      - db

networks:
  finance:
    driver: bridge
